import { NextResponse } from 'next/server';
import { ProfileRepository } from '@/lib/database/repositories/profileRepository';
import { withErrorHandling } from '@/lib/utils/errorHandler';
import { ValidationError } from '@/lib/errors/ApiError';
import { ProfileUpdateSchema } from '@/lib/validation/schemas';
import type { UserProfile } from '@/lib/types/health';

export async function GET() {
  const repo = new ProfileRepository();
  return withErrorHandling(async () => {
    const profile = repo.getProfile();
    if (!profile) {
      throw new ValidationError('Profile not found', 404);
    }
    const targets = repo.calculateNutritionalTargets();
    return NextResponse.json({ ...profile, targets });
  }, 'GET /api/profile');
}

export async function POST(request: Request) {
  const repo = new ProfileRepository();
  return withErrorHandling(async () => {
    console.log('[DEBUG] POST /api/profile called');
    
    const body = await request.json();
    console.log('[DEBUG] Request body:', body);
    
    // Validate required fields for profile creation
    const requiredFields = ['age', 'weight', 'height', 'gender', 'activityLevel'];
    for (const field of requiredFields) {
      if (!(field in body)) {
        console.log(`[DEBUG] Missing field: ${field}`);
        throw new ValidationError(`Missing required field: ${field}`, 400);
      }
    }

    // Check if profile exists
    const existing = repo.getProfile();
    
    const profile: UserProfile = {
      id: existing?.id || '', // Will be generated by createProfile if new
      age: body.age,
      weight: body.weight,
      height: body.height,
      gender: body.gender,
      activityLevel: body.activityLevel,
      displayName: body.displayName || undefined,
      healthConditions: body.healthConditions || [],
      allergies: body.allergies || [],
      createdAt: existing?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    let result;
    if (existing) {
      console.log('[DEBUG] Profile exists, updating...');
      repo.updateProfile(profile);
      result = repo.getProfile();
    } else {
      console.log('[DEBUG] Creating new profile...');
      result = repo.createProfile(profile);
    }
    
    const updated = repo.getProfile();
    console.log('[DEBUG] Profile operation successful:', updated?.id);
    
    const targets = repo.calculateNutritionalTargets();
    console.log('[DEBUG] Nutritional targets calculated');

    return NextResponse.json(
      { 
        ...updated, 
        targets, 
        message: existing ? 'Profile updated successfully' : `Profile created with ID: ${updated?.id}` 
      },
      { status: existing ? 200 : 201 }
    );
  }, 'POST /api/profile');
}

export async function PUT(request: Request) {
  const repo = new ProfileRepository();
  return withErrorHandling(async () => {
    const body = await request.json();
    const validated = ProfileUpdateSchema.parse(body);
    repo.updateProfile(validated);
    const updatedProfile = repo.getProfile();
    return NextResponse.json(updatedProfile);
  }, 'PUT /api/profile');
}
