import type { UserProfile, NutritionalTargets } from '@/lib/types/health';
import { calculateNutritionalTargets } from '@/lib/utils/nutritionalCalculator';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const PROFILE_PATH = path.join(process.cwd(), 'data', 'profile.json');

// Profile input type - createdAt/updatedAt are generated by the repository
export type ProfileInput = Omit<UserProfile, 'createdAt' | 'updatedAt'>;

export class ProfileRepository {
  private ensureDataDirectory(): void {
    const dataDir = path.dirname(PROFILE_PATH);
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }
  }

  private generateProfileId(displayName?: string): string {
    // Create a unique ID based on displayName + timestamp + random hash
    const name = displayName || 'user';
    const timestamp = Date.now();
    const hash = crypto
      .createHash('md5')
      .update(`${name}-${timestamp}`)
      .digest('hex')
      .substring(0, 8);
    return `${name.toLowerCase().replace(/\s+/g, '-')}-${hash}`;
  }

  getProfile(): UserProfile | null {
    try {
      if (!fs.existsSync(PROFILE_PATH)) {
        return null;
      }
      const data = fs.readFileSync(PROFILE_PATH, 'utf-8');
      return JSON.parse(data);
    } catch (error) {
      console.error('Error reading profile:', error);
      return null;
    }
  }

  createProfile(profile: ProfileInput): UserProfile {
    this.ensureDataDirectory();

    const id = this.generateProfileId(profile.displayName);
    const now = new Date().toISOString();

    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('🆔 PROFILE ID GENERATED');
    console.log('Display Name:', profile.displayName || '(none)');
    console.log('Generated ID:', id);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

    const newProfile: UserProfile = {
      ...profile,
      id,
      createdAt: now,
      updatedAt: now,
    };

    try {
      fs.writeFileSync(PROFILE_PATH, JSON.stringify(newProfile, null, 2), 'utf-8');
      console.log('[ProfileRepository] ✅ Profile created successfully');
      console.log('[ProfileRepository] Profile ID:', id);
      console.log('[ProfileRepository] File path:', PROFILE_PATH);
      return newProfile;
    } catch (error) {
      console.error('[ERROR] ❌ Failed to create profile:', error);
      throw error;
    }
  }

  updateProfile(profile: Partial<UserProfile>): void {
    const current = this.getProfile();
    if (!current) throw new Error('Profile not found');

    const updated: UserProfile = {
      ...current,
      ...profile,
      id: current.id, // Preserve original ID
      createdAt: current.createdAt, // Preserve creation date
      updatedAt: new Date().toISOString(),
    };

    try {
      fs.writeFileSync(PROFILE_PATH, JSON.stringify(updated, null, 2), 'utf-8');
      console.log('[ProfileRepository] Profile updated:', updated.id);
    } catch (error) {
      console.error('[ERROR] Failed to update profile:', error);
      throw error;
    }
  }

  calculateNutritionalTargets(): NutritionalTargets {
    const profile = this.getProfile();
    if (!profile) throw new Error('Profile not found');
    return calculateNutritionalTargets(profile);
  }
}
