/**
 * Realistic Food Nutrition Database
 * Provides accurate macro and micronutrient data per 100g serving
 * Based on USDA FoodData Central and FDA recommendations
 */

import type { NutritionalValues } from '@/lib/types/health';

// Food categories for realistic meal generation
export type FoodCategory =
  | 'protein'
  | 'grain'
  | 'vegetable'
  | 'fruit'
  | 'dairy'
  | 'fat'
  | 'snack'
  | 'beverage';

export interface FoodItem {
  id: string;
  name: string;
  category: FoodCategory;
  servingSize: number; // grams (typically 100g or 1 serving)
  caloriesPer100g: number;
  macros: {
    protein: number; // grams per 100g
    carbs: number; // grams per 100g
    fat: number; // grams per 100g
    fiber: number; // grams per 100g
    sugar: number; // grams per 100g
    sodium: number; // mg per 100g
  };
  micronutrients: {
    // Vitamins (mg or mcg)
    vitaminA: number; // mcg RAE
    vitaminC: number; // mg
    vitaminD: number; // mcg
    vitaminE?: number; // mg alpha-tocopherol (optional - many foods don't have data)
    vitaminK: number; // mcg
    thiamin: number; // mg (B1)
    riboflavin: number; // mg (B2)
    niacin: number; // mg (B3)
    vitaminB6: number; // mg
    folate: number; // mcg DFE
    vitaminB12: number; // mcg
    // Minerals (mg)
    calcium: number; // mg
    iron: number; // mg
    magnesium: number; // mg
    potassium: number; // mg
    zinc: number; // mg
    selenium: number; // mcg
  };
}

// Comprehensive food database with realistic nutrition values
export const foodDatabase: FoodItem[] = [
  // === PROTEINS ===
  {
    id: 'chicken_breast',
    name: 'Grilled Chicken Breast',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 165,
    macros: { protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, sodium: 74 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0.1,
      vitaminK: 0,
      thiamin: 0.07,
      riboflavin: 0.1,
      niacin: 13.5,
      vitaminB6: 0.6,
      folate: 4,
      vitaminB12: 0.3,
      calcium: 15,
      iron: 1,
      magnesium: 29,
      potassium: 256,
      zinc: 1,
      selenium: 22,
    },
  },
  {
    id: 'salmon',
    name: 'Baked Salmon',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 208,
    macros: { protein: 20, carbs: 0, fat: 13, fiber: 0, sugar: 0, sodium: 59 },
    micronutrients: {
      vitaminA: 50,
      vitaminC: 0,
      vitaminD: 11,
      vitaminK: 0,
      thiamin: 0.2,
      riboflavin: 0.2,
      niacin: 8.8,
      vitaminB6: 0.9,
      folate: 7,
      vitaminB12: 3.2,
      calcium: 12,
      iron: 0.8,
      magnesium: 29,
      potassium: 363,
      zinc: 0.6,
      selenium: 46,
    },
  },
  {
    id: 'ground_turkey',
    name: 'Ground Turkey (93% lean)',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 150,
    macros: { protein: 26, carbs: 0, fat: 4, fiber: 0, sugar: 0, sodium: 85 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0.1,
      vitaminK: 0,
      thiamin: 0.05,
      riboflavin: 0.15,
      niacin: 6.5,
      vitaminB6: 0.6,
      folate: 6,
      vitaminB12: 0.4,
      calcium: 18,
      iron: 1.2,
      magnesium: 27,
      potassium: 285,
      zinc: 2,
      selenium: 28,
    },
  },
  {
    id: 'beef_steak',
    name: 'Grilled Beef Steak',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 271,
    macros: { protein: 26, carbs: 0, fat: 18, fiber: 0, sugar: 0, sodium: 54 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0.1,
      vitaminK: 1,
      thiamin: 0.1,
      riboflavin: 0.2,
      niacin: 5.5,
      vitaminB6: 0.5,
      folate: 6,
      vitaminB12: 2.5,
      calcium: 18,
      iron: 2.6,
      magnesium: 22,
      potassium: 318,
      zinc: 5.5,
      selenium: 22,
    },
  },
  {
    id: 'eggs',
    name: 'Whole Eggs (scrambled)',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 149,
    macros: { protein: 13, carbs: 1.1, fat: 10.6, fiber: 0, sugar: 1.1, sodium: 149 },
    micronutrients: {
      vitaminA: 160,
      vitaminC: 0,
      vitaminD: 2,
      vitaminK: 0.3,
      thiamin: 0.1,
      riboflavin: 0.3,
      niacin: 0.1,
      vitaminB6: 0.1,
      folate: 24,
      vitaminB12: 0.9,
      calcium: 52,
      iron: 1.8,
      magnesium: 12,
      potassium: 138,
      zinc: 1.3,
      selenium: 23,
    },
  },
  {
    id: 'tofu',
    name: 'Firm Tofu',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 76,
    macros: { protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, sugar: 0.6, sodium: 7 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 2,
      thiamin: 0.05,
      riboflavin: 0.1,
      niacin: 0.2,
      vitaminB6: 0.1,
      folate: 15,
      vitaminB12: 0,
      calcium: 350,
      iron: 5.4,
      magnesium: 58,
      potassium: 121,
      zinc: 0.8,
      selenium: 9,
    },
  },
  {
    id: 'tuna',
    name: 'Canned Tuna',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 116,
    macros: { protein: 26, carbs: 0, fat: 1, fiber: 0, sugar: 0, sodium: 320 },
    micronutrients: {
      vitaminA: 20,
      vitaminC: 0,
      vitaminD: 1.7,
      vitaminK: 0,
      thiamin: 0.05,
      riboflavin: 0.1,
      niacin: 8.5,
      vitaminB6: 0.4,
      folate: 2,
      vitaminB12: 2.2,
      calcium: 11,
      iron: 1.3,
      magnesium: 30,
      potassium: 237,
      zinc: 0.8,
      selenium: 65,
    },
  },
  {
    id: 'shrimp',
    name: 'Cooked Shrimp',
    category: 'protein',
    servingSize: 100,
    caloriesPer100g: 99,
    macros: { protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sugar: 0, sodium: 111 },
    micronutrients: {
      vitaminA: 54,
      vitaminC: 0,
      vitaminD: 0.1,
      vitaminK: 0,
      thiamin: 0.02,
      riboflavin: 0.03,
      niacin: 1.5,
      vitaminB6: 0.1,
      folate: 3,
      vitaminB12: 1.1,
      calcium: 70,
      iron: 0.5,
      magnesium: 39,
      potassium: 259,
      zinc: 1.6,
      selenium: 45,
    },
  },
  // === GRAINS ===
  {
    id: 'white_rice',
    name: 'White Rice (cooked)',
    category: 'grain',
    servingSize: 100,
    caloriesPer100g: 130,
    macros: { protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sugar: 0.1, sodium: 1 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0.02,
      niacin: 0.4,
      vitaminB6: 0.1,
      folate: 58,
      vitaminB12: 0,
      calcium: 10,
      iron: 0.2,
      magnesium: 12,
      potassium: 35,
      zinc: 0.5,
      selenium: 7,
    },
  },
  {
    id: 'brown_rice',
    name: 'Brown Rice (cooked)',
    category: 'grain',
    servingSize: 100,
    caloriesPer100g: 112,
    macros: { protein: 2.6, carbs: 24, fat: 0.9, fiber: 1.8, sugar: 0.4, sodium: 5 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0.2,
      thiamin: 0.1,
      riboflavin: 0.02,
      niacin: 0.4,
      vitaminB6: 0.1,
      folate: 4,
      vitaminB12: 0,
      calcium: 10,
      iron: 0.5,
      magnesium: 43,
      potassium: 79,
      zinc: 0.6,
      selenium: 9,
    },
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal (cooked)',
    category: 'grain',
    servingSize: 100,
    caloriesPer100g: 71,
    macros: { protein: 2.5, carbs: 12, fat: 1.5, fiber: 1.7, sugar: 0.5, sodium: 49 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0.02,
      niacin: 0.2,
      vitaminB6: 0,
      folate: 10,
      vitaminB12: 0,
      calcium: 9,
      iron: 0.9,
      magnesium: 27,
      potassium: 61,
      zinc: 0.6,
      selenium: 4,
    },
  },
  {
    id: 'whole_wheat_bread',
    name: 'Whole Wheat Bread',
    category: 'grain',
    servingSize: 100,
    caloriesPer100g: 247,
    macros: { protein: 13, carbs: 41, fat: 3.4, fiber: 7, sugar: 6, sodium: 400 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 7,
      thiamin: 0.3,
      riboflavin: 0.1,
      niacin: 4,
      vitaminB6: 0.2,
      folate: 30,
      vitaminB12: 0,
      calcium: 161,
      iron: 2.5,
      magnesium: 75,
      potassium: 254,
      zinc: 1.8,
      selenium: 28,
    },
  },
  {
    id: 'pasta',
    name: 'Pasta (cooked)',
    category: 'grain',
    servingSize: 100,
    caloriesPer100g: 131,
    macros: { protein: 5, carbs: 25, fat: 1.1, fiber: 1.8, sugar: 0.6, sodium: 1 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0.05,
      niacin: 0.7,
      vitaminB6: 0,
      folate: 83,
      vitaminB12: 0,
      calcium: 7,
      iron: 1.3,
      magnesium: 18,
      potassium: 44,
      zinc: 0.5,
      selenium: 15,
    },
  },
  {
    id: 'quinoa',
    name: 'Quinoa (cooked)',
    category: 'grain',
    servingSize: 100,
    caloriesPer100g: 120,
    macros: { protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, sugar: 0.9, sodium: 7 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.4,
      vitaminB6: 0.1,
      folate: 42,
      vitaminB12: 0,
      calcium: 17,
      iron: 1.5,
      magnesium: 64,
      potassium: 172,
      zinc: 1.1,
      selenium: 2,
    },
  },
  // === VEGETABLES ===
  {
    id: 'broccoli',
    name: 'Steamed Broccoli',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 35,
    macros: { protein: 2.4, carbs: 7.2, fat: 0.4, fiber: 3.3, sugar: 1.4, sodium: 41 },
    micronutrients: {
      vitaminA: 77,
      vitaminC: 65,
      vitaminD: 0,
      vitaminK: 102,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.6,
      vitaminB6: 0.2,
      folate: 63,
      vitaminB12: 0,
      calcium: 40,
      iron: 0.7,
      magnesium: 21,
      potassium: 293,
      zinc: 0.4,
      selenium: 2,
    },
  },
  {
    id: 'spinach',
    name: 'Raw Spinach',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 23,
    macros: { protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4, sodium: 79 },
    micronutrients: {
      vitaminA: 469,
      vitaminC: 28,
      vitaminD: 0,
      vitaminK: 483,
      thiamin: 0.1,
      riboflavin: 0.2,
      niacin: 0.7,
      vitaminB6: 0.2,
      folate: 194,
      vitaminB12: 0,
      calcium: 99,
      iron: 2.7,
      magnesium: 79,
      potassium: 558,
      zinc: 0.5,
      selenium: 1,
    },
  },
  {
    id: 'carrots',
    name: 'Raw Carrots',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 41,
    macros: { protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7, sodium: 69 },
    micronutrients: {
      vitaminA: 835,
      vitaminC: 6,
      vitaminD: 0,
      vitaminK: 13,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.3,
      vitaminB6: 0.1,
      folate: 24,
      vitaminB12: 0,
      calcium: 33,
      iron: 0.3,
      magnesium: 12,
      potassium: 320,
      zinc: 0.2,
      selenium: 0.3,
    },
  },
  {
    id: 'sweet_potato',
    name: 'Baked Sweet Potato',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 90,
    macros: { protein: 2, carbs: 21, fat: 0.1, fiber: 3.3, sugar: 6.5, sodium: 36 },
    micronutrients: {
      vitaminA: 961,
      vitaminC: 20,
      vitaminD: 0,
      vitaminK: 2,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.6,
      vitaminB6: 0.3,
      folate: 6,
      vitaminB12: 0,
      calcium: 38,
      iron: 0.7,
      magnesium: 27,
      potassium: 475,
      zinc: 0.3,
      selenium: 0.6,
    },
  },
  {
    id: 'bell_pepper',
    name: 'Raw Bell Pepper',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 26,
    macros: { protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sugar: 4.2, sodium: 4 },
    micronutrients: {
      vitaminA: 157,
      vitaminC: 128,
      vitaminD: 0,
      vitaminK: 5,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.4,
      vitaminB6: 0.3,
      folate: 46,
      vitaminB12: 0,
      calcium: 7,
      iron: 0.4,
      magnesium: 12,
      potassium: 211,
      zinc: 0.3,
      selenium: 0.1,
    },
  },
  {
    id: 'tomatoes',
    name: 'Raw Tomatoes',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 18,
    macros: { protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6, sodium: 5 },
    micronutrients: {
      vitaminA: 42,
      vitaminC: 14,
      vitaminD: 0,
      vitaminK: 8,
      thiamin: 0,
      riboflavin: 0,
      niacin: 0.5,
      vitaminB6: 0.1,
      folate: 18,
      vitaminB12: 0,
      calcium: 10,
      iron: 0.3,
      magnesium: 11,
      potassium: 237,
      zinc: 0.2,
      selenium: 0,
    },
  },
  {
    id: 'cucumber',
    name: 'Raw Cucumber',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 15,
    macros: { protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7, sodium: 2 },
    micronutrients: {
      vitaminA: 5,
      vitaminC: 2.8,
      vitaminD: 0,
      vitaminK: 16,
      thiamin: 0,
      riboflavin: 0,
      niacin: 0.1,
      vitaminB6: 0,
      folate: 7,
      vitaminB12: 0,
      calcium: 16,
      iron: 0.3,
      magnesium: 13,
      potassium: 147,
      zinc: 0.2,
      selenium: 0,
    },
  },
  {
    id: 'asparagus',
    name: 'Steamed Asparagus',
    category: 'vegetable',
    servingSize: 100,
    caloriesPer100g: 22,
    macros: { protein: 2.2, carbs: 3.9, fat: 0.2, fiber: 2.1, sugar: 1.3, sodium: 2 },
    micronutrients: {
      vitaminA: 51,
      vitaminC: 5.6,
      vitaminD: 0,
      vitaminK: 52,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.9,
      vitaminB6: 0.1,
      folate: 149,
      vitaminB12: 0,
      calcium: 24,
      iron: 2.1,
      magnesium: 14,
      potassium: 202,
      zinc: 0.5,
      selenium: 2,
    },
  },
  // === FRUITS ===
  {
    id: 'apple',
    name: 'Raw Apple',
    category: 'fruit',
    servingSize: 100,
    caloriesPer100g: 52,
    macros: { protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sugar: 10, sodium: 1 },
    micronutrients: {
      vitaminA: 3,
      vitaminC: 5,
      vitaminD: 0,
      vitaminK: 2,
      thiamin: 0,
      riboflavin: 0,
      niacin: 0.1,
      vitaminB6: 0,
      folate: 3,
      vitaminB12: 0,
      calcium: 6,
      iron: 0.1,
      magnesium: 5,
      potassium: 107,
      zinc: 0,
      selenium: 0,
    },
  },
  {
    id: 'banana',
    name: 'Raw Banana',
    category: 'fruit',
    servingSize: 100,
    caloriesPer100g: 89,
    macros: { protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sugar: 12, sodium: 1 },
    micronutrients: {
      vitaminA: 3,
      vitaminC: 9,
      vitaminD: 0,
      vitaminK: 0.5,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.7,
      vitaminB6: 0.4,
      folate: 24,
      vitaminB12: 0,
      calcium: 5,
      iron: 0.3,
      magnesium: 27,
      potassium: 358,
      zinc: 0.2,
      selenium: 1,
    },
  },
  {
    id: 'blueberries',
    name: 'Raw Blueberries',
    category: 'fruit',
    servingSize: 100,
    caloriesPer100g: 57,
    macros: { protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, sugar: 10, sodium: 1 },
    micronutrients: {
      vitaminA: 3,
      vitaminC: 10,
      vitaminD: 0,
      vitaminK: 19,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.4,
      vitaminB6: 0.1,
      folate: 6,
      vitaminB12: 0,
      calcium: 6,
      iron: 0.3,
      magnesium: 6,
      potassium: 77,
      zinc: 0.2,
      selenium: 0.1,
    },
  },
  {
    id: 'strawberries',
    name: 'Raw Strawberries',
    category: 'fruit',
    servingSize: 100,
    caloriesPer100g: 32,
    macros: { protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, sugar: 4.9, sodium: 1 },
    micronutrients: {
      vitaminA: 1,
      vitaminC: 59,
      vitaminD: 0,
      vitaminK: 2,
      thiamin: 0,
      riboflavin: 0,
      niacin: 0.4,
      vitaminB6: 0,
      folate: 24,
      vitaminB12: 0,
      calcium: 16,
      iron: 0.4,
      magnesium: 13,
      potassium: 153,
      zinc: 0.1,
      selenium: 0.4,
    },
  },
  {
    id: 'orange',
    name: 'Raw Orange',
    category: 'fruit',
    servingSize: 100,
    caloriesPer100g: 47,
    macros: { protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, sugar: 9, sodium: 0 },
    micronutrients: {
      vitaminA: 11,
      vitaminC: 53,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0,
      niacin: 0.4,
      vitaminB6: 0.1,
      folate: 30,
      vitaminB12: 0,
      calcium: 40,
      iron: 0.1,
      magnesium: 10,
      potassium: 181,
      zinc: 0.1,
      selenium: 0.1,
    },
  },
  {
    id: 'grapes',
    name: 'Raw Grapes',
    category: 'fruit',
    servingSize: 100,
    caloriesPer100g: 69,
    macros: { protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, sugar: 16, sodium: 2 },
    micronutrients: {
      vitaminA: 3,
      vitaminC: 3,
      vitaminD: 0,
      vitaminK: 15,
      thiamin: 0.1,
      riboflavin: 0,
      niacin: 0.2,
      vitaminB6: 0.1,
      folate: 2,
      vitaminB12: 0,
      calcium: 10,
      iron: 0.4,
      magnesium: 7,
      potassium: 191,
      zinc: 0.1,
      selenium: 0.1,
    },
  },
  // === DAIRY ===
  {
    id: 'greek_yogurt',
    name: 'Greek Yogurt (plain, nonfat)',
    category: 'dairy',
    servingSize: 100,
    caloriesPer100g: 59,
    macros: { protein: 10, carbs: 3.6, fat: 0.7, fiber: 0, sugar: 3.2, sodium: 36 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0,
      riboflavin: 0.1,
      niacin: 0.1,
      vitaminB6: 0.1,
      folate: 7,
      vitaminB12: 0.8,
      calcium: 110,
      iron: 0.1,
      magnesium: 11,
      potassium: 141,
      zinc: 0.5,
      selenium: 5,
    },
  },
  {
    id: 'cottage_cheese',
    name: 'Cottage Cheese (low-fat)',
    category: 'dairy',
    servingSize: 100,
    caloriesPer100g: 82,
    macros: { protein: 11, carbs: 3.4, fat: 2.3, fiber: 0, sugar: 2.7, sodium: 348 },
    micronutrients: {
      vitaminA: 23,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0,
      riboflavin: 0.1,
      niacin: 0.1,
      vitaminB6: 0.1,
      folate: 12,
      vitaminB12: 0.4,
      calcium: 103,
      iron: 0.1,
      magnesium: 9,
      potassium: 104,
      zinc: 0.4,
      selenium: 9,
    },
  },
  {
    id: 'milk',
    name: 'Whole Milk',
    category: 'dairy',
    servingSize: 100,
    caloriesPer100g: 61,
    macros: { protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 5, sodium: 43 },
    micronutrients: {
      vitaminA: 46,
      vitaminC: 0,
      vitaminD: 1.3,
      vitaminK: 0.3,
      thiamin: 0.1,
      riboflavin: 0.2,
      niacin: 0.1,
      vitaminB6: 0,
      folate: 5,
      vitaminB12: 0.5,
      calcium: 113,
      iron: 0.1,
      magnesium: 10,
      potassium: 132,
      zinc: 0.4,
      selenium: 3,
    },
  },
  {
    id: 'cheddar_cheese',
    name: 'Cheddar Cheese',
    category: 'dairy',
    servingSize: 100,
    caloriesPer100g: 403,
    macros: { protein: 25, carbs: 1.3, fat: 33, fiber: 0, sugar: 0.5, sodium: 621 },
    micronutrients: {
      vitaminA: 210,
      vitaminC: 0,
      vitaminD: 0.6,
      vitaminK: 2.8,
      thiamin: 0,
      riboflavin: 0.4,
      niacin: 0.1,
      vitaminB6: 0.1,
      folate: 5,
      vitaminB12: 0.8,
      calcium: 721,
      iron: 0.7,
      magnesium: 28,
      potassium: 98,
      zinc: 3.1,
      selenium: 21,
    },
  },
  // === FATS ===
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    category: 'fat',
    servingSize: 100,
    caloriesPer100g: 884,
    macros: { protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, sodium: 2 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 60,
      thiamin: 0,
      riboflavin: 0,
      niacin: 0,
      vitaminB6: 0,
      folate: 0,
      vitaminB12: 0,
      calcium: 1,
      iron: 0.6,
      magnesium: 0,
      potassium: 1,
      zinc: 0,
      selenium: 0,
    },
  },
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'fat',
    servingSize: 100,
    caloriesPer100g: 579,
    macros: { protein: 21, carbs: 22, fat: 50, fiber: 12, sugar: 4.4, sodium: 1 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.2,
      riboflavin: 1,
      niacin: 3.6,
      vitaminB6: 0.1,
      folate: 44,
      vitaminB12: 0,
      calcium: 269,
      iron: 3.7,
      magnesium: 270,
      potassium: 733,
      zinc: 3.1,
      selenium: 4,
    },
  },
  {
    id: 'avocado',
    name: 'Raw Avocado',
    category: 'fat',
    servingSize: 100,
    caloriesPer100g: 160,
    macros: { protein: 2, carbs: 9, fat: 15, fiber: 7, sugar: 0.7, sodium: 7 },
    micronutrients: {
      vitaminA: 7,
      vitaminC: 10,
      vitaminD: 0,
      vitaminK: 21,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 1.7,
      vitaminB6: 0.3,
      folate: 81,
      vitaminB12: 0,
      calcium: 12,
      iron: 0.6,
      magnesium: 29,
      potassium: 485,
      zinc: 0.6,
      selenium: 0.4,
    },
  },
  {
    id: 'peanut_butter',
    name: 'Peanut Butter',
    category: 'fat',
    servingSize: 100,
    caloriesPer100g: 588,
    macros: { protein: 25, carbs: 20, fat: 50, fiber: 6, sugar: 9, sodium: 17 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0.3,
      thiamin: 0.1,
      riboflavin: 0.2,
      niacin: 12,
      vitaminB6: 0.4,
      folate: 24,
      vitaminB12: 0,
      calcium: 43,
      iron: 1.9,
      magnesium: 154,
      potassium: 649,
      zinc: 2.8,
      selenium: 4,
    },
  },
  // === SNACKS ===
  {
    id: 'protein_bar',
    name: 'Protein Bar',
    category: 'snack',
    servingSize: 100,
    caloriesPer100g: 380,
    macros: { protein: 30, carbs: 35, fat: 12, fiber: 4, sugar: 15, sodium: 200 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 2,
      vitaminB6: 0.2,
      folate: 30,
      vitaminB12: 0.5,
      calcium: 100,
      iron: 2,
      magnesium: 50,
      potassium: 200,
      zinc: 1.5,
      selenium: 10,
    },
  },
  {
    id: 'trail_mix',
    name: 'Trail Mix',
    category: 'snack',
    servingSize: 100,
    caloriesPer100g: 462,
    macros: { protein: 14, carbs: 44, fat: 28, fiber: 5, sugar: 30, sodium: 50 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 2,
      thiamin: 0.2,
      riboflavin: 0.2,
      niacin: 2.5,
      vitaminB6: 0.1,
      folate: 20,
      vitaminB12: 0,
      calcium: 100,
      iron: 3,
      magnesium: 150,
      potassium: 400,
      zinc: 2,
      selenium: 5,
    },
  },
  {
    id: 'hummus',
    name: 'Hummus',
    category: 'snack',
    servingSize: 100,
    caloriesPer100g: 166,
    macros: { protein: 8, carbs: 14, fat: 10, fiber: 6, sugar: 0.9, sodium: 364 },
    micronutrients: {
      vitaminA: 1,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 4,
      thiamin: 0.1,
      riboflavin: 0.1,
      niacin: 0.4,
      vitaminB6: 0.1,
      folate: 40,
      vitaminB12: 0,
      calcium: 49,
      iron: 2.4,
      magnesium: 49,
      potassium: 228,
      zinc: 1,
      selenium: 2,
    },
  },
  {
    id: 'rice_cakes',
    name: 'Rice Cakes',
    category: 'snack',
    servingSize: 100,
    caloriesPer100g: 387,
    macros: { protein: 8, carbs: 82, fat: 3, fiber: 4, sugar: 0, sodium: 420 },
    micronutrients: {
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0,
      niacin: 4.3,
      vitaminB6: 0.1,
      folate: 8,
      vitaminB12: 0,
      calcium: 10,
      iron: 0.8,
      magnesium: 50,
      potassium: 76,
      zinc: 1,
      selenium: 8,
    },
  },
  // === BEVERAGES ===
  {
    id: 'orange_juice',
    name: 'Orange Juice',
    category: 'beverage',
    servingSize: 100,
    caloriesPer100g: 45,
    macros: { protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, sugar: 8, sodium: 1 },
    micronutrients: {
      vitaminA: 10,
      vitaminC: 50,
      vitaminD: 0,
      vitaminK: 0,
      thiamin: 0.1,
      riboflavin: 0,
      niacin: 0.2,
      vitaminB6: 0,
      folate: 24,
      vitaminB12: 0,
      calcium: 27,
      iron: 0.2,
      magnesium: 11,
      potassium: 200,
      zinc: 0.1,
      selenium: 0.1,
    },
  },
  {
    id: 'smoothie',
    name: 'Fruit Smoothie',
    category: 'beverage',
    servingSize: 100,
    caloriesPer100g: 60,
    macros: { protein: 1, carbs: 13, fat: 0.5, fiber: 1.5, sugar: 10, sodium: 10 },
    micronutrients: {
      vitaminA: 5,
      vitaminC: 30,
      vitaminD: 0,
      vitaminK: 5,
      thiamin: 0.05,
      riboflavin: 0.05,
      niacin: 0.3,
      vitaminB6: 0.1,
      folate: 15,
      vitaminB12: 0,
      calcium: 30,
      iron: 0.3,
      magnesium: 10,
      potassium: 150,
      zinc: 0.1,
      selenium: 1,
    },
  },
];

/**
 * Get foods by category
 */
export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return foodDatabase.filter((food) => food.category === category);
}

/**
 * Get a random food from a category
 */
export function getRandomFood(category: FoodCategory): FoodItem {
  const foods = getFoodsByCategory(category);
  return foods[Math.floor(Math.random() * foods.length)];
}

/**
 * Get multiple random foods from a category
 */
export function getRandomFoods(category: FoodCategory, count: number): FoodItem[] {
  const foods = getFoodsByCategory(category);
  const shuffled = foods.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

/**
 * Get food by ID
 */
export function getFoodById(id: string): FoodItem | undefined {
  return foodDatabase.find((food) => food.id === id);
}

/**
 * Calculate nutrition for a given amount of food
 */
export function calculateNutrition(food: FoodItem, amount: number): NutritionalValues {
  const multiplier = amount / 100; // Per 100g base

  return {
    calories: Math.round(food.caloriesPer100g * multiplier),
    protein: parseFloat((food.macros.protein * multiplier).toFixed(1)),
    carbs: parseFloat((food.macros.carbs * multiplier).toFixed(1)),
    fat: parseFloat((food.macros.fat * multiplier).toFixed(1)),
    fiber: parseFloat((food.macros.fiber * multiplier).toFixed(1)),
    sugar: parseFloat((food.macros.sugar * multiplier).toFixed(1)),
    sodium: Math.round(food.macros.sodium * multiplier),
    calcium: Math.round(food.micronutrients.calcium * multiplier),
    iron: parseFloat((food.micronutrients.iron * multiplier).toFixed(2)),
    potassium: Math.round(food.micronutrients.potassium * multiplier),
    vitaminA: Math.round(food.micronutrients.vitaminA * multiplier),
    vitaminC: parseFloat((food.micronutrients.vitaminC * multiplier).toFixed(1)),
    vitaminD: parseFloat((food.micronutrients.vitaminD * multiplier).toFixed(2)),
    vitaminE:
      food.micronutrients.vitaminE !== undefined
        ? parseFloat((food.micronutrients.vitaminE * multiplier).toFixed(2))
        : undefined,
    vitaminK: parseFloat((food.micronutrients.vitaminK * multiplier).toFixed(1)),
    thiamin: parseFloat((food.micronutrients.thiamin * multiplier).toFixed(3)),
    riboflavin: parseFloat((food.micronutrients.riboflavin * multiplier).toFixed(3)),
    niacin: parseFloat((food.micronutrients.niacin * multiplier).toFixed(2)),
    vitaminB6: parseFloat((food.micronutrients.vitaminB6 * multiplier).toFixed(3)),
    folate: Math.round(food.micronutrients.folate * multiplier),
    vitaminB12: parseFloat((food.micronutrients.vitaminB12 * multiplier).toFixed(2)),
    magnesium: parseFloat((food.micronutrients.magnesium * multiplier).toFixed(1)),
    zinc: parseFloat((food.micronutrients.zinc * multiplier).toFixed(2)),
    selenium: parseFloat((food.micronutrients.selenium * multiplier).toFixed(1)),
  };
}

/**
 * Aggregate nutrition from multiple foods
 */
export function aggregateNutrition(nutritionList: NutritionalValues[]): NutritionalValues {
  return nutritionList.reduce((acc, nutrition) => {
    const result = { ...acc };

    // Sum macros and key micros
    const sumFields: (keyof NutritionalValues)[] = [
      'calories',
      'protein',
      'carbs',
      'fat',
      'fiber',
      'sugar',
      'sodium',
      'calcium',
      'iron',
      'potassium',
      'magnesium',
      'zinc',
      'selenium',
      'vitaminA',
      'vitaminC',
      'vitaminD',
      'vitaminE',
      'vitaminK',
      'thiamin',
      'riboflavin',
      'niacin',
      'vitaminB6',
      'folate',
      'vitaminB12',
    ];

    for (const field of sumFields) {
      if (nutrition[field] !== undefined) {
        result[field] = (result[field] || 0) + (nutrition[field] as number);
      }
    }

    return result;
  }, {} as NutritionalValues);
}
