-- [DO NOT EDIT THIS FILE DIRECTLY]
-- All schema changes MUST be made via migrations in src/lib/database/migrations/
-- This file is only for reference and fresh database initialization.

-- ============================================================
-- SECURITY NOTE: User Profile Data
-- ============================================================
-- User profile data (age, weight, height, gender, etc.) is stored
-- in data/profile.json ONLY, NOT in the database.
-- This ensures sensitive personal information is kept separate
-- from the database for security purposes.
-- Profile ID is still referenced in other tables but WITHOUT FK constraints.
-- ============================================================

-- User Conditions
CREATE TABLE IF NOT EXISTS user_conditions (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL
);

-- User Allergies
CREATE TABLE IF NOT EXISTS user_allergies (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL
);

-- Nutritional Targets
CREATE TABLE IF NOT EXISTS nutritional_targets (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  calories REAL NOT NULL,
  protein REAL NOT NULL,
  carbs REAL NOT NULL,
  fat REAL NOT NULL,
  fiber REAL NOT NULL,
  vitamin_a REAL,
  vitamin_c REAL,
  vitamin_d REAL,
  vitamin_e REAL,
  vitamin_k REAL,
  thiamin REAL,
  riboflavin REAL,
  niacin REAL,
  vitamin_b6 REAL,
  folate REAL,
  vitamin_b12 REAL,
  calcium REAL,
  iron REAL,
  magnesium REAL,
  potassium REAL,
  zinc REAL,
  selenium REAL,
  created_at TEXT NOT NULL
);

-- Foods Database
CREATE TABLE IF NOT EXISTS foods (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  serving_size REAL NOT NULL,
  serving_unit TEXT NOT NULL,
  calories REAL NOT NULL,
  protein REAL NOT NULL,
  carbs REAL NOT NULL,
  fat REAL NOT NULL,
  fiber REAL,
  sugar REAL,
  calcium REAL,
  iron REAL,
  sodium REAL,
  potassium REAL,
  vitamin_a REAL,
  vitamin_c REAL,
  vitamin_d REAL,
  brand_name TEXT,
  ingredients TEXT,
  allergens TEXT, -- JSON array
  source TEXT DEFAULT 'manual', -- 'manual' | 'mock' | 'usda'
  usda_fdc_id TEXT, -- USDA FoodData Central ID
  created_at TEXT NOT NULL
);

-- Index for USDA food lookups
CREATE INDEX IF NOT EXISTS idx_foods_usda_fdc_id ON foods(usda_fdc_id);

-- User's Supplements
CREATE TABLE IF NOT EXISTS supplements (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  serving_size TEXT NOT NULL,
  nutrients TEXT NOT NULL, -- JSON
  notes TEXT,
  color TEXT DEFAULT '#6366f1',
  dosage_frequency TEXT DEFAULT 'daily', -- 'daily' | 'weekly'
  dosage_quantity INTEGER DEFAULT 1,
  dosage_notes TEXT,
  created_at TEXT NOT NULL
);

-- Daily Meal Logs
CREATE TABLE IF NOT EXISTS meal_logs (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  meal_type TEXT NOT NULL,
  foods TEXT NOT NULL, -- JSON array
  total_nutrition TEXT NOT NULL, -- JSON
  created_at TEXT NOT NULL
);

-- Daily Supplement Logs
CREATE TABLE IF NOT EXISTS supplement_logs (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  supplement_id TEXT NOT NULL,
  supplement_name TEXT NOT NULL,
  taken INTEGER NOT NULL, -- boolean as 0/1
  taken_at TEXT, -- ISO timestamp for exact time taken
  created_at TEXT NOT NULL,
  FOREIGN KEY (supplement_id) REFERENCES supplements(id)
);

-- Supplement Nutrient Targets (custom overrides for RDA)
CREATE TABLE IF NOT EXISTS supplement_nutrient_targets (
  id TEXT PRIMARY KEY,
  nutrient_key TEXT NOT NULL UNIQUE,
  target_value REAL NOT NULL,
  use_rda INTEGER DEFAULT 1, -- 1 = use RDA, 0 = use custom target_value
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Daily Summary
CREATE TABLE IF NOT EXISTS daily_summary (
  date TEXT PRIMARY KEY,
  weight REAL,
  total_nutrition TEXT NOT NULL, -- JSON
  health_score REAL NOT NULL,
  notes TEXT,
  created_at TEXT NOT NULL
);

-- Calorie Goals - User's weight loss/gain/maintenance targets
CREATE TABLE IF NOT EXISTS calorie_goals (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  goal_type TEXT NOT NULL, -- 'weight_loss' | 'maintenance' | 'gain'
  weekly_calorie_target INTEGER NOT NULL, -- deficit/surplus per week (e.g., -3500 for 1lb loss)
  daily_calorie_target INTEGER NOT NULL, -- calculated from weekly + TDEE
  activity_level TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT, -- null if current goal
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Calorie Goal History - Audit trail of goal changes
CREATE TABLE IF NOT EXISTS calorie_goal_history (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  calorie_goal_id TEXT NOT NULL,
  action TEXT NOT NULL, -- 'created' | 'updated' | 'archived'
  previous_daily_target INTEGER,
  new_daily_target INTEGER,
  change_reason TEXT,
  changed_at TEXT NOT NULL,
  FOREIGN KEY (calorie_goal_id) REFERENCES calorie_goals(id)
);

-- Daily Calorie Tracking - Track daily progress toward goals
CREATE TABLE IF NOT EXISTS daily_calorie_tracking (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL UNIQUE,
  profile_id TEXT NOT NULL,
  calories_consumed INTEGER NOT NULL,
  calories_target INTEGER NOT NULL,
  calories_deficit_surplus INTEGER, -- negative = deficit, positive = surplus
  goal_met INTEGER DEFAULT 0, -- 1 = met, 0 = missed
  weekly_total_consumed INTEGER,
  weekly_total_target INTEGER,
  weekly_average INTEGER,
  on_pace_percentage INTEGER, -- 0-100+ how close to weekly goal
  trend TEXT, -- 'up', 'down', 'stable'
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Calorie Streaks - Track consecutive days meeting calorie goals
CREATE TABLE IF NOT EXISTS calorie_streaks (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  streak_start_date TEXT NOT NULL,
  streak_end_date TEXT, -- null if ongoing
  days_count INTEGER NOT NULL,
  goal_met_count INTEGER NOT NULL, -- days where deficit/surplus was met
  best_streak INTEGER DEFAULT 0,
  created_at TEXT NOT NULL
);

-- Weight Logs - Track weight over time
CREATE TABLE IF NOT EXISTS weight_logs (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  weight REAL NOT NULL,
  date TEXT NOT NULL, -- ISO 8601 date (YYYY-MM-DD)
  notes TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(profile_id, date) -- One weight entry per day per profile
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_calorie_goals_profile_id ON calorie_goals(profile_id);
CREATE INDEX IF NOT EXISTS idx_calorie_goals_start_date ON calorie_goals(start_date);
CREATE INDEX IF NOT EXISTS idx_calorie_goal_history_profile_id ON calorie_goal_history(profile_id);
CREATE INDEX IF NOT EXISTS idx_calorie_goal_history_goal_id ON calorie_goal_history(calorie_goal_id);
CREATE INDEX IF NOT EXISTS idx_daily_calorie_tracking_date ON daily_calorie_tracking(date);
CREATE INDEX IF NOT EXISTS idx_daily_calorie_tracking_profile_id ON daily_calorie_tracking(profile_id);
CREATE INDEX IF NOT EXISTS idx_calorie_streaks_profile_id ON calorie_streaks(profile_id);
CREATE INDEX IF NOT EXISTS idx_calorie_streaks_start_date ON calorie_streaks(streak_start_date);
CREATE INDEX IF NOT EXISTS idx_weight_logs_profile_date ON weight_logs(profile_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_meal_logs_date ON meal_logs(date);
CREATE INDEX IF NOT EXISTS idx_supplement_logs_date ON supplement_logs(date);
CREATE INDEX IF NOT EXISTS idx_foods_name ON foods(name);
CREATE INDEX IF NOT EXISTS idx_supplement_logs_date_id ON supplement_logs(date, supplement_id);
CREATE INDEX IF NOT EXISTS idx_nutritional_targets_profile_id ON nutritional_targets(profile_id);
CREATE INDEX IF NOT EXISTS idx_supplement_nutrient_targets_key ON supplement_nutrient_targets(nutrient_key);
CREATE INDEX IF NOT EXISTS idx_daily_summary_date ON daily_summary(date);
